FORMAT: 1A
HOST: http://127.0.0.1:8000
# Basic ACME Blog API
Welcome to the **ACME Blog** API. This API provides access to the **ACME Blog** service.
# Group Blog Posts
## Posts [GET /api/post]
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "id": 1,
                    "title": "foo title",
                    "body": "bar body",
                    "author": 1
                }
            ]
# Group Authors
Resources in this groups are related to **ACME Blog** authors.
## Authors [GET /api/author]
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "id": 1,
                    "name": "jhon",
                    "email": "jhon@mail.com"
                }
            ]