FORMAT: 1A
# Example

Example is simple example. (Hah!)

# Questions  [/]
add 

## GET [GET]
simple get question
+ Response 200 (application/json; charset=utf-8)

        {"message": "Nandej si chleba s halusky"}